name: WeatherApp
options:
  bundleIdPrefix: com.tertiaryinfotech
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "1.1"
    CURRENT_PROJECT_VERSION: "5"
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: NO
targets:
  WeatherApp:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tertiaryinfotech.weatherapp
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: GU9WTSTX9M
